import type { Metadata } from "next";
import { Press_Start_2P } from "next/font/google";
import "./globals.css";
import { SDKProvider } from "@tma.js/sdk-react"

const pressstart2p = Press_Start_2P({
  subsets: ["cyrillic", "latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SDKProvider acceptCustomStyles>
        <body className={pressstart2p.className}>{children}</body>
      </SDKProvider>
    </html>
  );
}
